# Generated by Django 5.0.2 on 2024-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default=None, upload_to='fiie/image/'),
        ),
    ]
